// Doctor Catalog with Illiterate-Friendly Visual Icons, Hindi/English labels, and Audio Prompts
const DOCTORS = [
  {
    id: "doc-1",
    nameEn: "Dr. Rajesh Sharma",
    nameHi: "डॉ. राजेश शर्मा",
    specialtyEn: "General Physician (Fever, Cough, Cold)",
    specialtyHi: "सामान्य चिकित्सक (बुखार, खांसी, जुकाम)",
    bodyPart: "Whole Body / बुखार",
    symptomIcon: "🤒",
    badgeColor: "#ef4444",
    badgeBg: "#fee2e2",
    room: "Room 101 (कमरा १०१)",
    roomNumber: 101,
    experience: "15+ Years",
    opdTime: "09:00 AM - 02:00 PM",
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
    voicePromptEn: "Doctor Rajesh Sharma. Room 101. For fever, cough, body pain and weakness.",
    voicePromptHi: "डॉक्टर राजेश शर्मा। कमरा नंबर १०१। बुखार, खांसी, बदन दर्द और सामान्य बीमारी के लिए।"
  },
  {
    id: "doc-2",
    nameEn: "Dr. Priya Patel",
    nameHi: "डॉ. प्रिया पटेल",
    specialtyEn: "Pediatrician (Child Specialist)",
    specialtyHi: "शिशु रोग विशेषज्ञ (बच्चों के डॉक्टर)",
    bodyPart: "Children / बच्चे",
    symptomIcon: "👶",
    badgeColor: "#ec4899",
    badgeBg: "#fce7f3",
    room: "Room 102 (कमरा १०२)",
    roomNumber: 102,
    experience: "12+ Years",
    opdTime: "10:00 AM - 03:00 PM",
    photo: "https://images.unsplash.com/photo-1594824813579-994119335eb2?w=300&auto=format&fit=crop&q=80",
    voicePromptEn: "Doctor Priya Patel. Room 102. Specialist for babies and young children.",
    voicePromptHi: "डॉक्टर प्रिया पटेल। कमरा नंबर १०२। छोटे बच्चों और शिशुओं की डॉक्टर।"
  },
  {
    id: "doc-3",
    nameEn: "Dr. Vikram Rao",
    nameHi: "डॉ. विक्रम राव",
    specialtyEn: "Cardiologist (Heart Specialist)",
    specialtyHi: "हृदय रोग विशेषज्ञ (दिल के डॉक्टर)",
    bodyPart: "Heart / दिल",
    symptomIcon: "❤️",
    badgeColor: "#dc2626",
    badgeBg: "#ffe4e6",
    room: "Room 103 (कमरा १०३)",
    roomNumber: 103,
    experience: "18+ Years",
    opdTime: "09:30 AM - 01:30 PM",
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
    voicePromptEn: "Doctor Vikram Rao. Room 103. Specialist for heart, chest pain, and blood pressure.",
    voicePromptHi: "डॉक्टर विक्रम राव। कमरा नंबर १०३। दिल की धड़कन, छाती दर्द और बीपी के डॉक्टर।"
  },
  {
    id: "doc-4",
    nameEn: "Dr. Sunita Verma",
    nameHi: "डॉ. सुनीता वर्मा",
    specialtyEn: "Orthopedic (Bone & Joint Specialist)",
    specialtyHi: "अस्थि रोग विशेषज्ञ (हड्डी व जोड़ों के डॉक्टर)",
    bodyPart: "Bones / हड्डी",
    symptomIcon: "🦴",
    badgeColor: "#0284c7",
    badgeBg: "#e0f2fe",
    room: "Room 104 (कमरा १०४)",
    roomNumber: 104,
    experience: "14+ Years",
    opdTime: "10:30 AM - 04:00 PM",
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
    voicePromptEn: "Doctor Sunita Verma. Room 104. Specialist for bone fracture, joint and back pain.",
    voicePromptHi: "डॉक्टर सुनीता वर्मा। कमरा नंबर १०४। हड्डी टूटना, जोड़ों का दर्द और कमर दर्द।"
  },
  {
    id: "doc-5",
    nameEn: "Dr. Amit Gupta",
    nameHi: "डॉ. अमित गुप्ता",
    specialtyEn: "Ophthalmologist (Eye Specialist)",
    specialtyHi: "नेत्र रोग विशेषज्ञ (आँखों के डॉक्टर)",
    bodyPart: "Eyes / आँखें",
    symptomIcon: "👁️",
    badgeColor: "#059669",
    badgeBg: "#d1fae5",
    room: "Room 105 (कमरा १०५)",
    roomNumber: 105,
    experience: "11+ Years",
    opdTime: "11:00 AM - 03:30 PM",
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
    voicePromptEn: "Doctor Amit Gupta. Room 105. Specialist for eye vision, glasses, and eye irritation.",
    voicePromptHi: "डॉक्टर अमित गुप्ता। कमरा नंबर १०५। आँखों की जांच, चश्मा और धुंधला दिखने पर।"
  },
  {
    id: "doc-6",
    nameEn: "Dr. Meenakshi Joshi",
    nameHi: "डॉ. मीनाक्षी जोशी",
    specialtyEn: "Dentist (Teeth Specialist)",
    specialtyHi: "दंत रोग विशेषज्ञ (दांतों के डॉक्टर)",
    bodyPart: "Teeth / दांत",
    symptomIcon: "🦷",
    badgeColor: "#7c3aed",
    badgeBg: "#ede9fe",
    room: "Room 106 (कमरा १०६)",
    roomNumber: 106,
    experience: "9+ Years",
    opdTime: "09:00 AM - 01:00 PM",
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300&auto=format&fit=crop&q=80",
    voicePromptEn: "Doctor Meenakshi Joshi. Room 106. Specialist for toothache, cleaning, and dental problems.",
    voicePromptHi: "डॉक्टर मीनाक्षी जोशी। कमरा नंबर १०६। दांत दर्द, मसूड़ों की समस्या और दांतों की सफाई।"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = DOCTORS;
}
