// Mock Data for OPD Token Booking Prototype (Hospitals, Doctors, Initial Queues, Translations)

const MOCK_HOSPITALS = [
  {
    id: "hosp-1",
    nameEn: "City Care Hospital",
    nameHi: "सिटी केयर अस्पताल",
    locationEn: "Main GT Road, Moga",
    locationHi: "मेन जीटी रोड, मोगा",
    statusEn: "Open Now",
    statusHi: "अभी खुला है",
    isOpen: true,
    timingEn: "08:00 AM - 08:00 PM",
    timingHi: "सुबह 08:00 - शाम 08:00",
    doctorCount: 3,
    phone: "01636-224488",
    image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=600&auto=format&fit=crop&q=80",
    badgeColor: "#10b981"
  },
  {
    id: "hosp-2",
    nameEn: "Civil District Hospital",
    nameHi: "सिविल जिला अस्पताल",
    locationEn: "Civil Lines, Moga",
    locationHi: "सिविल लाइन्स, मोगा",
    statusEn: "Open Now",
    statusHi: "अभी खुला है",
    isOpen: true,
    timingEn: "24 Hours Open",
    timingHi: "२४ घंटे खुला",
    doctorCount: 4,
    phone: "01636-220011",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80",
    badgeColor: "#0284c7"
  },
  {
    id: "hosp-3",
    nameEn: "LifeLine Superspeciality",
    nameHi: "लाइफलाइन सुपरस्पेशलिटी",
    locationEn: "Bypass Chowk, Moga",
    locationHi: "बाईपास चौक, मोगा",
    statusEn: "Open Now",
    statusHi: "अभी खुला है",
    isOpen: true,
    timingEn: "09:00 AM - 09:00 PM",
    timingHi: "सुबह 09:00 - रात 09:00",
    doctorCount: 5,
    phone: "01636-255999",
    image: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=600&auto=format&fit=crop&q=80",
    badgeColor: "#8b5cf6"
  }
];

const MOCK_DOCTORS = [
  {
    id: "doc-rajesh",
    hospitalId: "hosp-1",
    nameEn: "Dr. Rajesh Sharma",
    nameHi: "डॉ. राजेश शर्मा",
    specialtyEn: "Heart Specialist",
    specialtyHi: "दिल के डॉक्टर (हार्ट स्पेशलिस्ट)",
    symptomIcon: "❤️",
    room: "Room 204 (कमरा २०४)",
    roomNumber: "204",
    experience: "16+ Years Experience",
    experienceHi: "१६+ वर्षों का अनुभव",
    opdTime: "09:00 AM - 02:00 PM",
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    initialCurrentToken: 18,
    initialNextToken: 25, // Patient gets Token #25
    initialWaiting: 7,
    statusTextEn: "Available Today",
    statusTextHi: "आज उपस्थित हैं",
    voicePromptEn: "Doctor Rajesh Sharma. Heart Specialist. Room 204. Current token 18.",
    voicePromptHi: "डॉक्टर राजेश शर्मा। दिल के डॉक्टर। कमरा नंबर २०४। वर्तमान टोकन १८।"
  },
  {
    id: "doc-neha",
    hospitalId: "hosp-1",
    nameEn: "Dr. Neha Gupta",
    nameHi: "डॉ. नेहा गुप्ता",
    specialtyEn: "Child Specialist (Pediatrician)",
    specialtyHi: "बच्चों की डॉक्टर (शिशु विशेषज्ञ)",
    symptomIcon: "👶",
    room: "Room 102 (कमरा १०२)",
    roomNumber: "102",
    experience: "12+ Years Experience",
    experienceHi: "१२+ वर्षों का अनुभव",
    opdTime: "10:00 AM - 03:00 PM",
    photo: "https://images.unsplash.com/photo-1594824813579-994119335eb2?w=500&auto=format&fit=crop&q=80",
    initialCurrentToken: 11,
    initialNextToken: 15,
    initialWaiting: 4,
    statusTextEn: "Available Today",
    statusTextHi: "आज उपस्थित हैं",
    voicePromptEn: "Doctor Neha Gupta. Child Specialist. Room 102. Current token 11.",
    voicePromptHi: "डॉक्टर नेहा गुप्ता। बच्चों की डॉक्टर। कमra नंबर १०२। वर्तमान टोकन ११।"
  },
  {
    id: "doc-amit",
    hospitalId: "hosp-1",
    nameEn: "Dr. Amit Kumar",
    nameHi: "डॉ. अमित कुमार",
    specialtyEn: "General Physician (Fever, Cough, Cold)",
    specialtyHi: "सामान्य चिकित्सक (बुखार, खांसी, जुकाम)",
    symptomIcon: "🤒",
    room: "Room 105 (कमरा १०५)",
    roomNumber: "105",
    experience: "14+ Years Experience",
    experienceHi: "१४+ वर्षों का अनुभव",
    opdTime: "08:30 AM - 01:30 PM",
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80",
    initialCurrentToken: 16,
    initialNextToken: 22,
    initialWaiting: 6,
    statusTextEn: "Available Today",
    statusTextHi: "आज उपस्थित हैं",
    voicePromptEn: "Doctor Amit Kumar. General Physician. Room 105. Current token 16.",
    voicePromptHi: "डॉक्टर अमित कुमार। सामान्य चिकित्सक। कमरा नंबर १०५। वर्तमान टोकन १६।"
  }
];

// Initial realistic queue for Dr. Rajesh Sharma
const INITIAL_QUEUE_RAJESH = [
  { tokenNumber: 18, patientName: "Sukhwinder Singh", doctorId: "doc-rajesh", status: "CALLING", fee: 0, isFree: true, isUser: false },
  { tokenNumber: 19, patientName: "Aarti Devi", doctorId: "doc-rajesh", status: "WAITING", fee: 0, isFree: true, isUser: false },
  { tokenNumber: 20, patientName: "Harpreet Kaur", doctorId: "doc-rajesh", status: "WAITING", fee: 0, isFree: true, isUser: false },
  { tokenNumber: 21, patientName: "Patient A (Ramesh)", doctorId: "doc-rajesh", status: "WAITING", fee: 10, isFree: false, isUser: false },
  { tokenNumber: 22, patientName: "Patient B (Gurpreet)", doctorId: "doc-rajesh", status: "WAITING", fee: 10, isFree: false, isUser: false },
  { tokenNumber: 23, patientName: "Patient C (Manjit)", doctorId: "doc-rajesh", status: "WAITING", fee: 10, isFree: false, isUser: false },
  { tokenNumber: 24, patientName: "Patient D (Sunita)", doctorId: "doc-rajesh", status: "WAITING", fee: 10, isFree: false, isUser: false }
];

// UI Dictionaries for Hindi / English
const I18N = {
  en: {
    welcomeHeading: "Book Your Doctor Token From Home",
    welcomeSub: "No long lines. No hospital crowds. Book from home, come when your turn is near.",
    btnGetDoctorToken: "Get Doctor Token",
    btnFindHospital: "Find Hospital",
    btnMyToken: "My Token",
    btnHelp: "Help & Helpline",
    viewDoctors: "VIEW DOCTORS",
    openNow: "Open Now",
    availableToday: "Available Today",
    currentToken: "Current Token",
    peopleWaiting: "People Waiting",
    nextAvailableToken: "Next Available Token",
    getToken: "GET TOKEN",
    getMyToken: "🎟️ GET MY TOKEN",
    yourOpdToken: "YOUR OPD TOKEN",
    yourToken: "Your Token",
    peopleBeforeYou: "People Before You",
    estimatedWait: "Estimated Wait",
    statusPleaseWait: "PLEASE WAIT AT HOME",
    noQueueLine1: "You do not need to stand in the queue.",
    noQueueLine2: "Come to the hospital when your token is near.",
    btnTrackMyToken: "🔔 Track My Token",
    btnGoHome: "🏠 Go Home",
    yourTurn: "YOUR TURN",
    pleaseGoToRoom: "Please go to the OPD room.",
    viewHospitalDetails: "VIEW HOSPITAL DETAILS",
    turnIsComing: "Your turn is coming soon (2-3 people ahead)",
    startComing: "Please start coming to hospital now! (1 person ahead)",
    activeNow: "YOUR TOKEN IS NOW ACTIVE! PLEASE ENTER ROOM",
    waiting: "Waiting",
    completed: "Completed",
    calling: "Calling",
    first3Free: "FIRST 3 TOKENS FREE",
    after3Tokens: "₹10 / token after 3 tokens"
  },
  hi: {
    welcomeHeading: "घर बैठे डॉक्टर का टोकन लें",
    welcomeSub: "अस्पताल की लंबी कतारों से मुक्ति। घर पर टोकन लें, अपनी बारी आने पर ही जाएं।",
    btnGetDoctorToken: "🩺 टोकन प्राप्त करें",
    btnFindHospital: "🏥 अस्पताल चुनें",
    btnMyToken: "📋 मेरा टोकन",
    btnHelp: "☎️ सहायता एवं हेल्पलाइन",
    viewDoctors: "डॉक्टर देखें",
    openNow: "अभी खुला है",
    availableToday: "आज उपस्थित हैं",
    currentToken: "वर्तमान टोकन",
    peopleWaiting: "प्रतीक्षारत मरीज",
    nextAvailableToken: "आगामी टोकन",
    getToken: "टोकन लें",
    getMyToken: "🎟️ मेरा टोकन बनाएं",
    yourOpdToken: "आपका ओपीडी टोकन",
    yourToken: "आपका टोकन",
    peopleBeforeYou: "आपके आगे मरीज",
    estimatedWait: "अनुमानित समय",
    statusPleaseWait: "कृपया घर पर इंतज़ार करें",
    noQueueLine1: "आपको अस्पताल की लाइन में खड़े होने की जरूरत नहीं है।",
    noQueueLine2: "जब आपका टोकन पास आ जाए, तभी अस्पताल पधारें।",
    btnTrackMyToken: "🔔 मेरा टोकन ट्रैक करें",
    btnGoHome: "🏠 मुख्य पृष्ठ",
    yourTurn: "आपकी बारी आ गई है!",
    pleaseGoToRoom: "कृपया ओपीडी कक्ष में डॉक्टर के पास जाएं।",
    viewHospitalDetails: "अस्पताल का पता देखें",
    turnIsComing: "आपकी बारी आने वाली है (2-3 मरीज बाकी)",
    startComing: "कृपया अस्पताल के लिए रवाना हो जाएं! (1 मरीज बाकी)",
    activeNow: "आपका टोकन सक्रिय है! कृपया कमरे में प्रवेश करें",
    waiting: "प्रतीक्षारत",
    completed: "पूर्ण",
    calling: "बुलाया जा रहा है",
    first3Free: "पहले ३ टोकन मुफ़्त",
    after3Tokens: "३ टोकन के बाद मात्र ₹१० प्रति टोकन"
  }
};
